### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by zzz6519003** [madshargreave/gitchecker#1]
```
➜  gitchecker git:(master) ✗ ./start 
./start: line 1: .env: No such file or directory
```

**Comment by madshargreave** [comment]
Have you created the .env file described in the installation section of the readme?

**Comment by zzz6519003** [comment]
MY BAD! thx!

2016-01-12 11:45 GMT+08:00 Mads Hargreave notifications@github.com:

> Have you created the .env file described in the installation section of
> the readme?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/madshargreave/gitchecker/issues/1#issuecomment-170775910
> .

## 

yours,

正中赵
about.me/zzz6519003
[image: 正中赵 on about.me]
  http://about.me/zzz6519003
